#region generic sections for all tests
#Requires -Modules Az.Accounts, Az.PolicyInsights, Az.Resources
#Requires -Version 7.0

using module ../../../infra/pwsh/AzResourceTest/AzResourceTest.psd1

$helperFunctionScriptPath = (resolve-path -relativeBasePath $PSScriptRoot -path '../.shared/helper-functions.ps1').Path

#load helper
. $helperFunctionScriptPath

#Run initiate-test script to set environment variables for test configuration and deployment
$globalConfigFilePath = (resolve-path -RelativeBasePath $PSScriptRoot -path '../.shared/policy_integration_test_config.jsonc').Path
$TestDirectory = $PSScriptRoot
Write-Output "Initiating test with global config file: $globalConfigFilePath and test directory: $TestDirectory"
. ../.shared/initiate-test.ps1 -globalConfigFilePath $globalConfigFilePath -TestDirectory $TestDirectory

<#
The following script scoped variables are expected to be set before running the test initiation script (initiate-test.ps1):

- All configurations from the $globalConfigFilePath, with the prefix 'GlobalConfig_' added to the variable name. i.e. $script:GlobalConfig_deploymentPrefix
- All configurations from the $localConfigFilePath, with the prefix 'LocalConfig_' added to the variable name. i.e. $script:LocalConfig_testResourceGroup
- $script:token: the Azure OAuth token for the Azure control plane API endpoint (https://management.azure.com/), which is generated by the initiation script (initiate-test.ps1) using the Az PowerShell module.
- $script:testSubscriptionId: the subscription Id for testing, which should be set to one of the subscription Ids defined in the global config file.
- $script:bicepDeploymentOutputs: the outputs from test bicep template deployment, which should be set by the deployment script (deploy-policy-test-bicep-template.ps1) if the test bicep template is deployed successfully.
- $script:bicepProvisioningState: the provisioning state from test bicep template deployment, which should be set by the deployment script (deploy-policy-test-bicep-template.ps1).
- $script:deploymentTarget: the deployment target from test bicep template deployment, which should be set by the deployment script (deploy-policy-test-bicep-template.ps1).
- $script:testTitle: the Pester test title, which should be set to "$script:LocalConfig_testName Configuration Test" by the initiation script (initiate-test.ps1).
- $script:contextTitle: the Pester context title, which should be set to "$script:LocalConfig_testName Configuration" by the initiation script (initiate-test.ps1).
- $script:testSuiteName: the test suite name for test result output, which should be set to $script:LocalConfig_testName by the initiation script (initiate-test.ps1).
- $script:outputFilePath: the file path for test result output, which should be set to "$script:GlobalConfig_testOutputFilePrefix-$script:LocalConfig_testName.xml" by the initiation script (initiate-test.ps1).
- $script:whatIfComplyBicepTemplatePath: the absolute path for the bicep template used for What-If deployments that are expected to comply with the policy, which should be set to "$PSScriptRoot\$script:GlobalConfig_whatIfComplyBicepTemplateName" by the initiation script (initiate-test.ps1).
- $script:whatIfViolateBicepTemplatePath: the absolute path for the bicep template used for What-If deployments that are expected to violate the policy, which should be set to "$PSScriptRoot\$script:GlobalConfig_whatIfViolateBicepTemplateName" by the initiation script (initiate-test.ps1).
- $script:testTerraformDirectoryPath: the absolute path for the directory containing the Terraform configuration used for testing, which should be set to "$PSScriptRoot\$script:GlobalConfig_testTerraformDirectoryName" by the initiation script (initiate-test.ps1).
- $script:terraformBackendStateFileDirectory: the directory path for the Terraform backend state file, which should be set to "$PSScriptRoot\tf-state" by the initiation script (initiate-test.ps1).
- $script:terraformDeploymentOutputs: the outputs from test Terraform template deployment, which should be set by the deployment script (deploy-policy-test-terraform-template.ps1) if the test Terraform template is deployed successfully.
- $script:terraformProvisioningState: the provisioning state from test Terraform template deployment, which should be set by the deployment script (deploy-policy-test-terraform-template.ps1).
- $script:terraformViolateDirectoryPath: the directory path for the Terraform configuration used for validate against Policy Violation API that expected to violate deny or audit policies, which should be set to "$PSScriptRoot\$script:GlobalConfig_terraformViolateDirectoryName" by the initiation script (initiate-test.ps1).
- $script:terraformComplyDirectoryPath: the directory path for the Terraform configuration used for validate against Policy Violation API that expected to comply with the policy, which should be set to "$PSScriptRoot\$script:GlobalConfig_terraformComplyDirectoryName" by the initiation script (initiate-test.ps1).

#>

#endregion

#region test specific configuration and tests
<#
The following policy definitions are tested via both What-If deployment and Poilcy Restriction API.
In real world scenario, select one of the two methods as this is for demonstration purpose to show the flexibility of the test framework in supporting different test methods.
  - MON-001: Restrict Azure Monitor Action Group Send Email Notification to External Email Addresses (Deny)
  - MON-002: Restrict Azure Monitor Action Group Send SMS Notification to Unauthorized country codes (Deny)
  - MON-003: Restrict Azure Monitor Action Group Trigger Actions to Cross-Subscription Azure Automation or not on the Allowed List (Deny)
  - MON-004: Restrict Azure Monitor Action Group Trigger Actions to Cross-Subscription Event Hubs or not on the Allowed List (Deny)
  - MON-005: Restrict Azure Monitor Action Group Trigger Actions to Cross-Subscription Function Apps or not on the Allowed List (Deny)
  - MON-006: Restrict Azure Monitor Action Group Trigger Actions to Cross-Subscription Logic Apps or not on the Allowed List (Deny)
  - MON-007: Restrict Azure Monitor Action Group Trigger Actions to Webhooks that are not on the Allowed List (Deny)
  - MON-008: Restrict Azure Monitor Action Group Trigger Actions to Webhooks that are not using HTTPS (Deny)
#>


$actionGroupName = 'ag01'
$monitorAssignmentId = '/providers/Microsoft.Management/managementGroups/{0}/providers/Microsoft.Authorization/policyAssignments/{1}' -f $script:LocalConfig_testManagementGroup, $script:LocalConfig_assignmentName
$actionGroupViolatingResourceContent = @{
  properties = @{
    smsReceivers               = @(
      @{
        countryCode = '7' #Country code for Russia, should violate policy MON-002
        phoneNumber = '2345678901'
      }
    )
    emailReceivers             = @(
      @{
        emailAddress = 'test.user1@outlook.com' #violate policy MON-001
      }
    )
    automationRunbookReceivers = @(
      @{
        automationAccountId = '/subscriptions/62740b7e-8b53-4411-a353-14e023983d78/resourceGroups/rg-mon3-01/providers/Microsoft.Automation/automationAccounts/automationAccount1/webhooks/alert1' #violate policy MON-003
      }
    )
    eventHubReceivers          = @(
      @{
        eventHubNameSpace = '/subscriptions/62740b7e-8b53-4411-a353-14e023983d78/resourceGroups/rg-mon3-01/providers/Microsoft.EventHub/namespaces/eventHub1' #violate policy MON-004
      }
    )
    azureFunctionReceivers     = @(
      @{
        functionAppResourceId = '/subscriptions/62740b7e-8b53-4411-a353-14e023983d78/resourceGroups/rg-mon3-01/providers/Microsoft.Web/sites/functionApp1' #violate policy MON-005
      }
    )
    logicAppReceivers          = @(
      @{
        resourceId = '/subscriptions/62740b7e-8b53-4411-a353-14e023983d78/resourceGroups/rg-mon3-01/providers/Microsoft.Logic/workflows/logicApp1' #violate policy MON-006
      }
    )
    webhookReceivers           = @(
      @{
        serviceUri = 'http://webhookuri1.com' #violate policy MON-007 and MON-008
      }
    )
  }
} | ConvertTo-Json -Depth 99
Write-Output "Action Group Violating Resource Content: `n $actionGroupViolatingResourceContent"
$actionGroupViolatingResourceConfig = @{
  resourceName       = $actionGroupName
  resourceType       = 'Microsoft.Insights/actionGroups'
  apiVersion         = '2024-10-01-preview'
  resourceContent    = $actionGroupViolatingResourceContent
  location           = 'global'
  includeAuditEffect = $true
}
$policyRestrictionViolatingPolicies = @(
  @{
    policyAssignmentId          = $monitorAssignmentId
    policyDefinitionReferenceId = 'MON-001'
    resourceReference           = $actionGroupName
    policyEffect                = 'Deny'
  }
  @{
    policyAssignmentId          = $monitorAssignmentId
    policyDefinitionReferenceId = 'MON-002'
    resourceReference           = $actionGroupName
    policyEffect                = 'Deny'
  }
  @{
    policyAssignmentId          = $monitorAssignmentId
    policyDefinitionReferenceId = 'MON-003'
    resourceReference           = $actionGroupName
    policyEffect                = 'Deny'
  }
  @{
    policyAssignmentId          = $monitorAssignmentId
    policyDefinitionReferenceId = 'MON-004'
    resourceReference           = $actionGroupName
    policyEffect                = 'Deny'
  }
  @{
    policyAssignmentId          = $monitorAssignmentId
    policyDefinitionReferenceId = 'MON-005'
    resourceReference           = $actionGroupName
    policyEffect                = 'Deny'
  }
  @{
    policyAssignmentId          = $monitorAssignmentId
    policyDefinitionReferenceId = 'MON-006'
    resourceReference           = $actionGroupName
    policyEffect                = 'Deny'
  }
  @{
    policyAssignmentId          = $monitorAssignmentId
    policyDefinitionReferenceId = 'MON-007'
    resourceReference           = $actionGroupName
    policyEffect                = 'Deny'
  }
  @{
    policyAssignmentId          = $monitorAssignmentId
    policyDefinitionReferenceId = 'MON-008'
    resourceReference           = $actionGroupName
    policyEffect                = 'Deny'
  }
)

$whatIfViolatingPolicies = @(
  @{
    policyAssignmentId          = $monitorAssignmentId
    policyDefinitionReferenceId = 'MON-001'
  }
  @{
    policyAssignmentId          = $monitorAssignmentId
    policyDefinitionReferenceId = 'MON-002'
  }
  @{
    policyAssignmentId          = $monitorAssignmentId
    policyDefinitionReferenceId = 'MON-003'
  }
  @{
    policyAssignmentId          = $monitorAssignmentId
    policyDefinitionReferenceId = 'MON-004'
  }
  @{
    policyAssignmentId          = $monitorAssignmentId
    policyDefinitionReferenceId = 'MON-005'
  }
  @{
    policyAssignmentId          = $monitorAssignmentId
    policyDefinitionReferenceId = 'MON-006'
  }
  @{
    policyAssignmentId          = $monitorAssignmentId
    policyDefinitionReferenceId = 'MON-007'
  }
  @{
    policyAssignmentId          = $monitorAssignmentId
    policyDefinitionReferenceId = 'MON-008'
  }
)

#define tests
$tests = @()



$tests += New-ARTWhatIfDeploymentTestConfig 'Policy abiding deployment should succeed' $script:token $script:whatIfComplyBicepTemplatePath $script:deploymentTarget 'Succeeded' -maxRetry $script:GlobalConfig_whatIfMaxRetry
$tests += New-ARTWhatIfDeploymentTestConfig 'Policy violating deployment should fail' $script:token $script:whatIfViolateBicepTemplatePath $script:deploymentTarget 'Failed' $whatIfViolatingPolicies -maxRetry $script:GlobalConfig_whatIfMaxRetry

$tests += New-ARTArmPolicyRestrictionTestConfig -testName 'Action Group Configuration should violate deny policies' -token $script:token -deploymentTargetResourceId $script:deploymentTarget -resourceConfig $actionGroupViolatingResourceConfig -policyViolation $policyRestrictionViolatingPolicies

#Invoke tests
$params = @{
  tests         = $tests
  testTitle     = $script:testTitle
  contextTitle  = $script:contextTitle
  testSuiteName = $script:testSuiteName
  OutputFile    = $script:outputFilePath
  OutputFormat  = $script:GlobalConfig_testOutputFormat
}
Test-ARTResourceConfiguration @params

#endregion

#region post-test clean up. do not modify
Write-Output "Starting post-test cleanup."
. ../.shared/post-test-cleanup.ps1
Write-Output "$script:testTitle test execution completed."
#endregion