#region generic sections for all tests
#Requires -Modules Az.Accounts, Az.PolicyInsights, Az.Resources
#Requires -Version 7.0

using module ../../../infra/pwsh/AzResourceTest/AzResourceTest.psd1

$helperFunctionScriptPath = (resolve-path -relativeBasePath $PSScriptRoot -path '../.shared/helper-functions.ps1').Path

#load helper
. $helperFunctionScriptPath

#Run initiate-test script to set environment variables for test configuration and deployment
$globalConfigFilePath = (resolve-path -RelativeBasePath $PSScriptRoot -path '../.shared/policy_integration_test_config.jsonc').Path
$TestDirectory = $PSScriptRoot
Write-Output "Initiating test with global config file: $globalConfigFilePath and test directory: $TestDirectory"
. ../.shared/initiate-test.ps1 -globalConfigFilePath $globalConfigFilePath -TestDirectory $TestDirectory

<#
The following script scoped variables are expected to be set before running the test initiation script (initiate-test.ps1):

- All configurations from the $globalConfigFilePath, with the prefix 'GlobalConfig_' added to the variable name. i.e. $script:GlobalConfig_deploymentPrefix
- All configurations from the $localConfigFilePath, with the prefix 'LocalConfig_' added to the variable name. i.e. $script:LocalConfig_testResourceGroup
- $script:token: the Azure OAuth token for the Azure control plane API endpoint (https://management.azure.com/), which is generated by the initiation script (initiate-test.ps1) using the Az PowerShell module.
- $script:testSubscriptionId: the subscription Id for testing, which should be set to one of the subscription Ids defined in the global config file.
- $script:bicepDeploymentOutputs: the outputs from test bicep template deployment, which should be set by the deployment script (deploy-policy-test-bicep-template.ps1) if the test bicep template is deployed successfully.
- $script:bicepProvisioningState: the provisioning state from test bicep template deployment, which should be set by the deployment script (deploy-policy-test-bicep-template.ps1).
- $script:deploymentTarget: the deployment target from test bicep template deployment, which should be set by the deployment script (deploy-policy-test-bicep-template.ps1).
- $script:testTitle: the Pester test title, which should be set to "$script:LocalConfig_testName Configuration Test" by the initiation script (initiate-test.ps1).
- $script:contextTitle: the Pester context title, which should be set to "$script:LocalConfig_testName Configuration" by the initiation script (initiate-test.ps1).
- $script:testSuiteName: the test suite name for test result output, which should be set to $script:LocalConfig_testName by the initiation script (initiate-test.ps1).
- $script:outputFilePath: the file path for test result output, which should be set to "$script:GlobalConfig_testOutputFilePrefix-$script:LocalConfig_testName.xml" by the initiation script (initiate-test.ps1).
- $script:whatIfComplyBicepTemplatePath: the absolute path for the bicep template used for What-If deployments that are expected to comply with the policy, which should be set to "$PSScriptRoot\$script:GlobalConfig_whatIfComplyBicepTemplateName" by the initiation script (initiate-test.ps1).
- $script:whatIfViolateBicepTemplatePath: the absolute path for the bicep template used for What-If deployments that are expected to violate the policy, which should be set to "$PSScriptRoot\$script:GlobalConfig_whatIfViolateBicepTemplateName" by the initiation script (initiate-test.ps1).
- $script:testTerraformDirectoryPath: the absolute path for the directory containing the Terraform configuration used for testing, which should be set to "$PSScriptRoot\$script:GlobalConfig_testTerraformDirectoryName" by the initiation script (initiate-test.ps1).
- $script:terraformBackendStateFileDirectory: the directory path for the Terraform backend state file, which should be set to "$PSScriptRoot\tf-state" by the initiation script (initiate-test.ps1).
- $script:terraformDeploymentOutputs: the outputs from test Terraform template deployment, which should be set by the deployment script (deploy-policy-test-terraform-template.ps1) if the test Terraform template is deployed successfully.
- $script:terraformProvisioningState: the provisioning state from test Terraform template deployment, which should be set by the deployment script (deploy-policy-test-terraform-template.ps1).
- $script:terraformViolateDirectoryPath: the directory path for the Terraform configuration used for validate against Policy Violation API that expected to violate deny or audit policies, which should be set to "$PSScriptRoot\$script:GlobalConfig_terraformViolateDirectoryName" by the initiation script (initiate-test.ps1).
- $script:terraformComplyDirectoryPath: the directory path for the Terraform configuration used for validate against Policy Violation API that expected to comply with the policy, which should be set to "$PSScriptRoot\$script:GlobalConfig_terraformComplyDirectoryName" by the initiation script (initiate-test.ps1).

#>

#endregion

#region test specific configuration and tests
<#
The following policy definitions are tested:
  - Resource Group inherit the 'dataclass' tag from subscription
  - Resource Group inherit the 'owner' tag from subscription
  - Azure Key Vault should disable public network access (Audit)
  - Key Vault should have purge protection enabled (Modify)
  - Private DNS Record for Key Vault PE must exist (DeployIfNotExists)
  - Diagnostic Settings for Key Vault Must Be Configured (DeployIfNotExists)
  - KeyVault permission model should be configured to use Azure RBAC (Deny)
#>

#Parse Deployment outputs
$deploymentOutputsJson = $script:bicepDeploymentOutputs | ConvertFrom-Json -Depth 99
$resourceId = $deploymentOutputsJson.resourceId.value
$resourceName = ($resourceId -split ('/'))[-1]

#prepare other variables needed for tests
$privateDNSSubscriptionId = $script:GlobalConfig_subscriptions.$script:GlobalConfig_privateDNSSubscription.id
$privateDNSResourceGroup = $script:GlobalConfig_privateDNSResourceGroup
$keyVaultPolicyAssignmentId = '/providers/Microsoft.Management/managementGroups/{0}/providers/Microsoft.Authorization/policyAssignments/{1}' -f $script:LocalConfig_testManagementGroup, $script:LocalConfig_keyVaultAssignmentName
$diagnosticSettingsId = "{0}{1}" -f $resourceId, $script:GlobalConfig_diagnosticSettingsIdSuffix
$kvPrivateDNSARecordId = "/subscriptions/{0}/resourceGroups/{1}/providers/Microsoft.Network/privateDnsZones/privatelink.vaultcore.azure.net/A/{2}" -f $privateDNSSubscriptionId, $privateDNSResourceGroup, $resourceName

#define violating deny policies
$violatingPolicies = @(
  @{
    policyAssignmentId          = $keyVaultPolicyAssignmentId
    policyDefinitionReferenceId = 'KV-003' #KV-003: KeyVault permission model should be configured to use Azure RBAC
  }
)

#define tests
$tests = @()
#Modify / Append Policies

#TAG-006 rg-inherit-tag-from-sub (dataclass)
$tests += New-ARTPropertyCountTestConfig 'TAG-006: Resource Group Should have dataclass tag' $script:token $script:deploymentTarget 'tags.dataclass' 'equals' 1
$tests += New-ARTPropertyCountTestConfig 'TAG-007: Resource Group Should have owner tag' $script:token $script:deploymentTarget 'tags.owner' 'equals' 1
$tests += New-ARTPropertyValueTestConfig 'KV-002: Key Vault should have purge protection enabled' $script:token $resourceId 'boolean' 'properties.enablePurgeProtection' 'equals' $true

#Audit / AuditIfNotExists policies
$tests += New-ARTPolicyStateTestConfig 'KV-004: Azure Key Vault should disable public network access' $script:token $resourceId $keyVaultPolicyAssignmentId 'NonCompliant' 'KV-004'

#DeployIfNotExists Policies
$tests += New-ARTResourceExistenceTestConfig 'PEDNS-005: Private DNS Record for Key Vault PE must exist' $script:token $kvPrivateDNSARecordId 'exists'
$tests += New-ARTResourceExistenceTestConfig 'DS-029: Diagnostic Settings for Key Vault Must Be Configured' $script:token $diagnosticSettingsId 'exists' $script:GlobalConfig_diagnosticSettingsAPIVersion

#Deny policies (testing both positive and negative scenarios)
$tests += New-ARTWhatIfDeploymentTestConfig 'Policy abiding deployment should succeed' $script:token $script:whatIfComplyBicepTemplatePath $script:deploymentTarget 'Succeeded' -maxRetry $script:GlobalConfig_whatIfMaxRetry
$tests += New-ARTWhatIfDeploymentTestConfig 'Policy violating deployment should fail' $script:token $script:whatIfViolateBicepTemplatePath $script:deploymentTarget 'Failed' $violatingPolicies -maxRetry $script:GlobalConfig_whatIfMaxRetry

#Invoke tests
$params = @{
  tests         = $tests
  testTitle     = $script:testTitle
  contextTitle  = $script:contextTitle
  testSuiteName = $script:testSuiteName
  OutputFile    = $script:outputFilePath
  OutputFormat  = $script:GlobalConfig_testOutputFormat
}
Test-ARTResourceConfiguration @params

#endregion

#region post-test clean up. do not modify
# remove terraform deployed resources first
if ($script:terraformProvisioningState -ieq 'Succeeded') {
  Write-output "Remove Terraform deployed test resources."
  $tfDestroyParams = @{
    terraformPath               = $script:testTerraformDirectoryPath
    tfBackendConfigFileName     = $script:GlobalConfig_testTerraformBackendConfigFileName
    tfAction                    = 'destroy'
    tfBackendStateFileDirectory = $script:terraformBackendStateFileDirectory
    tfStateFileName             = $script:GlobalConfig_testTerraformStateFileName
    uninitializeTerraform       = $true
  }
  . ../.shared/deploy-destroy-policy-test-terraform-template.ps1 @tfDestroyParams
}

#determine if deployed resources should be removed based on deployment state and configuration
if ($script:bicepProvisioningState -ieq 'Succeeded' -or $script:LocalConfig_removeTestResourceGroup -eq 'true') {
  #delete deployed resources
  Write-output "Remove Bicep deployed test resources."
  . ../.shared/delete-policy-test-deployed-resources.ps1
}
#endregion