#region generic sections for all tests
#Requires -Modules Az.Accounts, Az.PolicyInsights, Az.Resources
#Requires -Version 7.0

using module ../../../infra/pwsh/AzResourceTest/AzResourceTest.psd1

$helperFunctionScriptPath = (resolve-path -relativeBasePath $PSScriptRoot -path '../.shared/helper-functions.ps1').Path

#load helper
. $helperFunctionScriptPath

#Run initiate-test script to set environment variables for test configuration and deployment
$globalConfigFilePath = (resolve-path -RelativeBasePath $PSScriptRoot -path '../.shared/policy_integration_test_config.jsonc').Path
$TestDirectory = $PSScriptRoot
Write-Output "Initiating test with global config file: $globalConfigFilePath and test directory: $TestDirectory"
. ../.shared/initiate-test.ps1 -globalConfigFilePath $globalConfigFilePath -TestDirectory $TestDirectory

<#
The following script scoped variables are expected to be set before running the test initiation script (initiate-test.ps1):

- All configurations from the $globalConfigFilePath, with the prefix 'GlobalConfig_' added to the variable name. i.e. $script:GlobalConfig_deploymentPrefix
- All configurations from the $localConfigFilePath, with the prefix 'LocalConfig_' added to the variable name. i.e. $script:LocalConfig_testResourceGroup
- $script:token: the Azure OAuth token for the Azure control plane API endpoint (https://management.azure.com/), which is generated by the initiation script (initiate-test.ps1) using the Az PowerShell module.
- $script:testSubscriptionId: the subscription Id for testing, which should be set to one of the subscription Ids defined in the global config file.
- $script:bicepDeploymentOutputs: the outputs from test bicep template deployment, which should be set by the deployment script (deploy-policy-test-bicep-template.ps1) if the test bicep template is deployed successfully.
- $script:bicepProvisioningState: the provisioning state from test bicep template deployment, which should be set by the deployment script (deploy-policy-test-bicep-template.ps1).
- $script:deploymentTarget: the deployment target from test bicep template deployment, which should be set by the deployment script (deploy-policy-test-bicep-template.ps1).
- $script:testTitle: the Pester test title, which should be set to "$script:LocalConfig_testName Configuration Test" by the initiation script (initiate-test.ps1).
- $script:contextTitle: the Pester context title, which should be set to "$script:LocalConfig_testName Configuration" by the initiation script (initiate-test.ps1).
- $script:testSuiteName: the test suite name for test result output, which should be set to $script:LocalConfig_testName by the initiation script (initiate-test.ps1).
- $script:outputFilePath: the file path for test result output, which should be set to "$script:GlobalConfig_testOutputFilePrefix-$script:LocalConfig_testName.xml" by the initiation script (initiate-test.ps1).
- $script:whatIfComplyBicepTemplatePath: the absolute path for the bicep template used for What-If deployments that are expected to comply with the policy, which should be set to "$PSScriptRoot\$script:GlobalConfig_whatIfComplyBicepTemplateName" by the initiation script (initiate-test.ps1).
- $script:whatIfViolateBicepTemplatePath: the absolute path for the bicep template used for What-If deployments that are expected to violate the policy, which should be set to "$PSScriptRoot\$script:GlobalConfig_whatIfViolateBicepTemplateName" by the initiation script (initiate-test.ps1).
- $script:testTerraformDirectoryPath: the absolute path for the directory containing the Terraform configuration used for testing, which should be set to "$PSScriptRoot\$script:GlobalConfig_testTerraformDirectoryName" by the initiation script (initiate-test.ps1).
- $script:terraformBackendStateFileDirectory: the directory path for the Terraform backend state file, which should be set to "$PSScriptRoot\tf-state" by the initiation script (initiate-test.ps1).
- $script:terraformDeploymentOutputs: the outputs from test Terraform template deployment, which should be set by the deployment script (deploy-policy-test-terraform-template.ps1) if the test Terraform template is deployed successfully.
- $script:terraformProvisioningState: the provisioning state from test Terraform template deployment, which should be set by the deployment script (deploy-policy-test-terraform-template.ps1).
- $script:terraformViolateDirectoryPath: the directory path for the Terraform configuration used for validate against Policy Violation API that expected to violate deny or audit policies, which should be set to "$PSScriptRoot\$script:GlobalConfig_terraformViolateDirectoryName" by the initiation script (initiate-test.ps1).
- $script:terraformComplyDirectoryPath: the directory path for the Terraform configuration used for validate against Policy Violation API that expected to comply with the policy, which should be set to "$PSScriptRoot\$script:GlobalConfig_terraformComplyDirectoryName" by the initiation script (initiate-test.ps1).

#>

#endregion

Write-Output "Terraform Deployment Outputs: $deploymentOutputs"

$deploymentOutputsJson = $script:terraformDeploymentOutputs | ConvertFrom-Json -Depth 99
$storageAccountId = $deploymentOutputsJson.storage_account_id.value
#$storageAccountBlobPeId = $deploymentOutputsJson.storage_account_blob_pe_id.value

$storagePolicyAssignmentId = '/providers/Microsoft.Management/managementGroups/{0}/providers/Microsoft.Authorization/policyAssignments/{1}' -f $script:LocalConfig_testManagementGroup, $script:LocalConfig_storageAccountAssignmentName

$diagnosticSettingsIdSuffix = '/providers/microsoft.insights/diagnosticSettings/setByPolicyLAW'
$diagnosticSettingsId = "{0}{1}" -f $storageAccountId, $diagnosticSettingsIdSuffix
$script:token = $(az account get-access-token --resource 'https://management.azure.com/' | convertfrom-json).accessToken

$violatingPolicies = @(
  @{
    policyAssignmentId          = $storagePolicyAssignmentId
    policyDefinitionReferenceId = 'STG-006'
    resourceReference           = 'azapi_resource.storage_account'
    policyEffect                = 'Deny'
  }
  @{
    policyAssignmentId          = $storagePolicyAssignmentId
    policyDefinitionReferenceId = 'STG-007'
    resourceReference           = 'azapi_resource.storage_account'
    policyEffect                = 'Audit'
  }
  @{
    policyAssignmentId          = $storagePolicyAssignmentId
    policyDefinitionReferenceId = 'STG-009'
    resourceReference           = 'azapi_resource.storage_account'
    policyEffect                = 'Deny'
  }
  @{
    policyAssignmentId          = $storagePolicyAssignmentId
    policyDefinitionReferenceId = 'STG-010'
    resourceReference           = 'azapi_resource.storage_account'
    policyEffect                = 'Deny'
  }
  @{
    policyAssignmentId          = $storagePolicyAssignmentId
    policyDefinitionReferenceId = 'STG-012'
    resourceReference           = 'azapi_resource.storage_account'
    policyEffect                = 'Deny'
  }
  @{
    policyAssignmentId          = $storagePolicyAssignmentId
    policyDefinitionReferenceId = 'STG-008'
    resourceReference           = 'azapi_resource.storage_account'
    policyEffect                = 'Deny'
  }

)
#define tests
$tests = @()

#Modify / Append Policies
#TAG-010 all-inherit-tag-from-rg (dataclass)
$tests += New-ARTPropertyCountTestConfig 'TAG-010: Resource Should have dataclass tag' $script:token $storageAccountId 'tags.dataclass' 'equals' 1

#TAG-011 all-inherit-tag-from-rg (owner)
$tests += New-ARTPropertyCountTestConfig 'TAG-011: Resource Should have owner tag' $script:token $storageAccountId 'tags.owner' 'equals' 1

$tests += New-ARTResourceExistenceTestConfig 'Diagnostic Settings Must Be Configured' $script:token $diagnosticSettingsId 'exists' $script:GlobalConfig_diagnosticSettingsAPIVersion

#Deny policies
$tests += New-ARTTerraformPolicyRestrictionTestConfig -testName 'Violating Audit and Deny Policies should be detected from test Terraform template' -token $script:token -terraformDirectory $script:terraformViolateDirectoryPath -policyViolation $violatingPolicies

#Invoke tests
$params = @{
  tests         = $tests
  testTitle     = $script:testTitle
  contextTitle  = $script:contextTitle
  testSuiteName = $script:testSuiteName
  OutputFile    = $script:outputFilePath
  OutputFormat  = $script:GlobalConfig_testOutputFormat
}
Test-ARTResourceConfiguration @params

#region post-test clean up. do not modify
# remove terraform deployed resources first
if ($script:terraformProvisioningState -ieq 'Succeeded') {
  Write-output "Remove Terraform deployed test resources."
  $tfDestroyParams = @{
    terraformPath               = $script:testTerraformDirectoryPath
    tfBackendConfigFileName     = $script:GlobalConfig_testTerraformBackendConfigFileName
    tfAction                    = 'destroy'
    tfBackendStateFileDirectory = $script:terraformBackendStateFileDirectory
    tfStateFileName             = $script:GlobalConfig_testTerraformStateFileName
    uninitializeTerraform       = $true
  }
  . ../.shared/deploy-destroy-policy-test-terraform-template.ps1 @tfDestroyParams
}

#determine if deployed resources should be removed based on deployment state and configuration
if ($script:bicepProvisioningState -ieq 'Succeeded' -or $script:LocalConfig_removeTestResourceGroup -eq 'true') {
  #delete deployed resources
  Write-output "Remove Bicep deployed test resources."
  . ../.shared/delete-policy-test-deployed-resources.ps1
}
#endregion