#region generic sections for all tests
#Requires -Modules Az.Accounts, Az.PolicyInsights, Az.Resources
#Requires -Version 7.0

using module ../../../infra/pwsh/AzResourceTest/AzResourceTest.psd1

$helperFunctionScriptPath = (resolve-path -relativeBasePath $PSScriptRoot -path '../.shared/helper-functions.ps1').Path

#load helper
. $helperFunctionScriptPath

#Run initiate-test script to set environment variables for test configuration and deployment
$globalConfigFilePath = (resolve-path -RelativeBasePath $PSScriptRoot -path '../.shared/policy_integration_test_config.jsonc').Path
$TestDirectory = $PSScriptRoot
Write-Output "Initiating test with global config file: $globalConfigFilePath and test directory: $TestDirectory"
. ../.shared/initiate-test.ps1 -globalConfigFilePath $globalConfigFilePath -TestDirectory $TestDirectory

<#
The following script scoped variables are expected to be set before running the test initiation script (initiate-test.ps1):

- All configurations from the $globalConfigFilePath, with the prefix 'GlobalConfig_' added to the variable name. i.e. $script:GlobalConfig_deploymentPrefix
- All configurations from the $localConfigFilePath, with the prefix 'LocalConfig_' added to the variable name. i.e. $script:LocalConfig_testResourceGroup
- $script:token: the Azure OAuth token for the Azure control plane API endpoint (https://management.azure.com/), which is generated by the initiation script (initiate-test.ps1) using the Az PowerShell module.
- $script:testSubscriptionId: the subscription Id for testing, which should be set to one of the subscription Ids defined in the global config file.
- $script:bicepDeploymentName: the deployment name for test bicep template deployment, which should be set by the deployment script (deploy-policy-test-bicep-template.ps1) if the test bicep template is deployed successfully.
- $script:bicepDeploymentId: the deployment Id for test bicep template deployment, which should be set by the deployment script (deploy-policy-test-bicep-template.ps1) if the test bicep template is deployed successfully.
- $script:deploymentTarget: the deployment target from test bicep template deployment, which should be set by the deployment script (deploy-policy-test-bicep-template.ps1).
- $script:bicepDeploymentScope: the deployment scope (subscription or resourcegroup) for test bicep template deployment, which should be set by the deployment script (deploy-policy-test-bicep-template.ps1).
- $script:bicepDeploymentOutputs: the outputs from test bicep template deployment, which should be set by the deployment script (deploy-policy-test-bicep-template.ps1) if the test bicep template is deployed successfully.
- $script:bicepProvisioningState: the provisioning state from test bicep template deployment, which should be set by the deployment script (deploy-policy-test-bicep-template.ps1).
- $script:deploymentTarget: the deployment target from test bicep template deployment, which should be set by the deployment script (deploy-policy-test-bicep-template.ps1).
- $script:testTitle: the Pester test title, which should be set to "$script:LocalConfig_testName Configuration Test" by the initiation script (initiate-test.ps1).
- $script:contextTitle: the Pester context title, which should be set to "$script:LocalConfig_testName Configuration" by the initiation script (initiate-test.ps1).
- $script:testSuiteName: the test suite name for test result output, which should be set to $script:LocalConfig_testName by the initiation script (initiate-test.ps1).
- $script:outputFilePath: the file path for test result output, which should be set to "$script:GlobalConfig_testOutputFilePrefix-$script:LocalConfig_testName.xml" by the initiation script (initiate-test.ps1).
- $script:whatIfComplyBicepTemplatePath: the absolute path for the bicep template used for What-If deployments that are expected to comply with the policy, which should be set to "$PSScriptRoot\$script:GlobalConfig_whatIfComplyBicepTemplateName" by the initiation script (initiate-test.ps1).
- $script:whatIfViolateBicepTemplatePath: the absolute path for the bicep template used for What-If deployments that are expected to violate the policy, which should be set to "$PSScriptRoot\$script:GlobalConfig_whatIfViolateBicepTemplateName" by the initiation script (initiate-test.ps1).
- $script:testTerraformDirectoryPath: the absolute path for the directory containing the Terraform configuration used for testing, which should be set to "$PSScriptRoot\$script:GlobalConfig_testTerraformDirectoryName" by the initiation script (initiate-test.ps1).
- $script:terraformBackendStateFileDirectory: the directory path for the Terraform backend state file, which should be set to "$PSScriptRoot\tf-state" by the initiation script (initiate-test.ps1).
- $script:terraformDeploymentOutputs: the outputs from test Terraform template deployment, which should be set by the deployment script (deploy-policy-test-terraform-template.ps1) if the test Terraform template is deployed successfully.
- $script:terraformProvisioningState: the provisioning state from test Terraform template deployment, which should be set by the deployment script (deploy-policy-test-terraform-template.ps1).
- $script:terraformViolateDirectoryPath: the directory path for the Terraform configuration used for validate against Policy Violation API that expected to violate deny or audit policies, which should be set to "$PSScriptRoot\$script:GlobalConfig_terraformViolateDirectoryName" by the initiation script (initiate-test.ps1).
- $script:terraformComplyDirectoryPath: the directory path for the Terraform configuration used for validate against Policy Violation API that expected to comply with the policy, which should be set to "$PSScriptRoot\$script:GlobalConfig_terraformComplyDirectoryName" by the initiation script (initiate-test.ps1).

#>
#endregion

<#
Test cases:
- TAG-001: Subscription Should have appid tag (deny)
- TAG-002: Subscription Should have dataclass tag with allowed value (deny)
- TAG-003: Subscription Should have owner tag (deny)
- TAG-004: Subscription Should have supportteam tag (deny)
- TAG-005: Inherit the tag from the Subscription to Resource Group if missing (appid)
- TAG-006: Inherit the tag from the Subscription to Resource Group if missing (dataclass)
- TAG-007: Inherit the tag from the Subscription to Resource Group if missing (owner)
- TAG-008: Inherit the tag from the Subscription to Resource Group if missing (supportteam)
- TAG-013: Resource Group Should have required tag value for dataclass tag (deny)
- TAG-014: Resource Should have required tag value for dataclass tag (deny)
- TAG-015: Subscription Should have required tag value for environment tag (deny)
- TAG-016: Resource Group Should have required tag value for environment tag (deny)
- TAG-017: Resource Should have required tag value for environment tag (deny)
- TAG-018: Inherit the tag from the Subscription to Resource Group if missing (environment)
#>

#variables

#Parse deployment outputs
$deploymentOutputsJson = $script:bicepDeploymentOutputs | ConvertFrom-Json -Depth 99
$resourceId = $deploymentOutputsJson.resourceId.value

#This test case uses non-standard bicep template names for what-if validation because it requires 2 separate templates. The template file names are defined in local config in this case.
$resourceWhatIfFailedTemplatePath = join-path $PSScriptRoot $script:LocalConfig_whatIfViolateBicepTemplateForResourcesName
$rgWhatIfFailedTemplatePath = join-path $PSScriptRoot $script:LocalConfig_whatIfViolateBicepTemplateForRGName

$resourceWhatIfDeploymentTargetResourceId = '/subscriptions/{0}/resourceGroups/{1}' -f $testSubscriptionId, $script:LocalConfig_testResourceGroup
$testSubscriptionResourceId = '/subscriptions/{0}' -f $script:testSubscriptionId


$taggingAssignmentId = '/providers/Microsoft.Management/managementGroups/{0}/providers/Microsoft.Authorization/policyAssignments/{1}' -f $script:LocalConfig_testManagementGroup, $script:LocalConfig_assignmentName


$subViolatingPolicies = @(
  @{
    policyAssignmentId          = $taggingAssignmentId
    policyDefinitionReferenceId = 'TAG-001'
  },
  @{
    policyAssignmentId          = $taggingAssignmentId
    policyDefinitionReferenceId = 'TAG-002'
  },
  @{
    policyAssignmentId          = $taggingAssignmentId
    policyDefinitionReferenceId = 'TAG-003'
  },
  @{
    policyAssignmentId          = $taggingAssignmentId
    policyDefinitionReferenceId = 'TAG-004'
  },
  @{
    policyAssignmentId          = $taggingAssignmentId
    policyDefinitionReferenceId = 'TAG-015'
  }
)

$rgViolatingPolicies = @(
  @{
    policyAssignmentId          = $taggingAssignmentId
    policyDefinitionReferenceId = 'TAG-013'
  },
  @{
    policyAssignmentId          = $taggingAssignmentId
    policyDefinitionReferenceId = 'TAG-016'
  }
)

$resourceViolatingPolicies = @(
  @{
    policyAssignmentId          = $taggingAssignmentId
    policyDefinitionReferenceId = 'TAG-014'
  },
  @{
    policyAssignmentId          = $taggingAssignmentId
    policyDefinitionReferenceId = 'TAG-017'
  }
)


#test sub update
$subViolatingTags = @{
  appid1       = '10207' #this should violate the policy TAG-001: Subscription Should have required tag (SolutionID)
  owner1       = 'platform-team' #this should violate the policy TAG-003: Subscription Should have required tag (owner)
  dataclass    = 'official-internal' #this should violate the policy TAG-002: Subscription Should have required tag value (dataclass). 'official-internal' is not one of the allowed values
  supportteam1 = 'platform-team' #this should violate the policy TAG-004: Subscription Should have required tag (supportteam)
  environment  = "hell" #this should violate the policy TAG-015: Subscription Should have required tag value (environment). 'hell' is not one of the allowed values
}


$subTagUpdateTestResponse = updateAzResourceTags -resourceId $testSubscriptionResourceId -tags $subViolatingTags -revertBack $true
$subTagUpdatePolicyActualVioations = ($subTagUpdateTestResponse.content | convertfrom-Json -depth 10).error.additionalInfo | Where-Object { $_.type -ieq 'policyviolation' }

#define tests
$tests = @()
$tests += New-ARTManualWhatIfTestConfig -testName 'Subscription Tagging Policy violating update should fail' -actualPolicyViolation $subTagUpdatePolicyActualVioations -desiredPolicyViolation $subViolatingPolicies
$tests += New-ARTWhatIfDeploymentTestConfig -testName 'Resource Group Tagging Policy violating deployment should fail' -token $token -templateFilePath $rgWhatIfFailedTemplatePath -deploymentTargetResourceId $testSubscriptionResourceId -requiredWhatIfStatus 'Failed' -policyViolation $rgViolatingPolicies -maxRetry $script:GlobalConfig_whatIfMaxRetry
$tests += New-ARTWhatIfDeploymentTestConfig -testName 'Resource Tagging Policy violating deployment should fail' -token $token -templateFilePath $resourceWhatIfFailedTemplatePath -deploymentTargetResourceId $resourceWhatIfDeploymentTargetResourceId -requiredWhatIfStatus 'Failed' -policyViolation $resourceViolatingPolicies -maxRetry $script:GlobalConfig_whatIfMaxRetry

#Modify / Append Policies
#TAG-005 rg-inherit-tag-from-sub (appid)
$tests += New-ARTPropertyCountTestConfig 'TAG-005: Resource Group Should have appid tag' $token $resourceId 'tags.appid' 'equals' 1

#TAG-006 rg-inherit-tag-from-sub (dataclass)
$tests += New-ARTPropertyCountTestConfig 'TAG-006: Resource Group Should have dataclass tag' $token $resourceId 'tags.dataclass' 'equals' 1

#TAG-007 rg-inherit-tag-from-sub (owner)
$tests += New-ARTPropertyCountTestConfig 'TAG-007: Resource Group Should have owner tag' $token $resourceId 'tags.owner' 'equals' 1

#TAG-008 rg-inherit-tag-from-sub (supportteam)
$tests += New-ARTPropertyCountTestConfig 'TAG-008: Resource Group Should have supportteam tag' $token $resourceId 'tags.supportteam' 'equals' 1

#TAG-018 rg-inherit-tag-from-sub (environment)
$tests += New-ARTPropertyCountTestConfig 'TAG-018: Resource Group Should have environment tag' $token $resourceId 'tags.environment' 'equals' 1

#Invoke tests
$params = @{
  tests         = $tests
  testTitle     = $script:testTitle
  contextTitle  = $script:contextTitle
  testSuiteName = $script:testSuiteName
  OutputFile    = $script:outputFilePath
  OutputFormat  = $script:GlobalConfig_testOutputFormat
}
Test-ARTResourceConfiguration @params
#endregion

#region post-test clean up. do not modify
Write-Output "Starting post-test cleanup."
. ../.shared/post-test-cleanup.ps1
Write-Output "$script:testTitle test execution completed."
#endregion
