#region generic sections for all tests - do not modify
#Requires -Modules Az.Accounts, Az.PolicyInsights, Az.Resources
#Requires -Version 7.0

using module ../../../infra/pwsh/AzResourceTest/AzResourceTest.psd1

$helperFunctionScriptPath = (resolve-path -relativeBasePath $PSScriptRoot -path '../.shared/helper-functions.ps1').Path

#load helper
. $helperFunctionScriptPath

#Run initiate-test script to set environment variables for test configuration and deployment
$globalConfigFilePath = (resolve-path -RelativeBasePath $PSScriptRoot -path '../.shared/policy_integration_test_config.jsonc').Path
$TestDirectory = $PSScriptRoot
Write-Output "Initiating test with global config file: $globalConfigFilePath and test directory: $TestDirectory"
. ../.shared/initiate-test.ps1 -globalConfigFilePath $globalConfigFilePath -TestDirectory $TestDirectory

<#
The following script scoped variables are expected to be set before running the test initiation script (initiate-test.ps1):

- All configurations from the $globalConfigFilePath, with the prefix 'GlobalConfig_' added to the variable name. i.e. $script:GlobalConfig_deploymentPrefix
- All configurations from the $localConfigFilePath, with the prefix 'LocalConfig_' added to the variable name. i.e. $script:LocalConfig_testResourceGroup
- $script:token: the Azure OAuth token for the Azure control plane API endpoint (https://management.azure.com/), which is generated by the initiation script (initiate-test.ps1) using the Az PowerShell module.
- $script:testSubscriptionId: the subscription Id for testing, which should be set to one of the subscription Ids defined in the global config file.
- $script:bicepDeploymentOutputs: the outputs from test bicep template deployment, which should be set by the deployment script (deploy-policy-test-bicep-template.ps1) if the test bicep template is deployed successfully.
- $script:bicepProvisioningState: the provisioning state from test bicep template deployment, which should be set by the deployment script (deploy-policy-test-bicep-template.ps1).
- $script:deploymentTarget: the deployment target from test bicep template deployment, which should be set by the deployment script (deploy-policy-test-bicep-template.ps1).
- $script:testTitle: the Pester test title, which should be set to "$script:LocalConfig_testName Configuration Test" by the initiation script (initiate-test.ps1).
- $script:contextTitle: the Pester context title, which should be set to "$script:LocalConfig_testName Configuration" by the initiation script (initiate-test.ps1).
- $script:testSuiteName: the test suite name for test result output, which should be set to $script:LocalConfig_testName by the initiation script (initiate-test.ps1).
- $script:outputFilePath: the file path for test result output, which should be set to "$script:GlobalConfig_testOutputFilePrefix-$script:LocalConfig_testName.xml" by the initiation script (initiate-test.ps1).
- $script:whatIfComplyBicepTemplatePath: the absolute path for the bicep template used for What-If deployments that are expected to comply with the policy, which should be set to "$PSScriptRoot\$script:GlobalConfig_whatIfComplyBicepTemplateName" by the initiation script (initiate-test.ps1).
- $script:whatIfViolateBicepTemplatePath: the absolute path for the bicep template used for What-If deployments that are expected to violate the policy, which should be set to "$PSScriptRoot\$script:GlobalConfig_whatIfViolateBicepTemplateName" by the initiation script (initiate-test.ps1).
- $script:testTerraformDirectoryPath: the absolute path for the directory containing the Terraform configuration used for testing, which should be set to "$PSScriptRoot\$script:GlobalConfig_testTerraformDirectoryName" by the initiation script (initiate-test.ps1).
- $script:terraformBackendStateFileDirectory: the directory path for the Terraform backend state file, which should be set to "$PSScriptRoot\tf-state" by the initiation script (initiate-test.ps1).
- $script:terraformDeploymentOutputs: the outputs from test Terraform template deployment, which should be set by the deployment script (deploy-policy-test-terraform-template.ps1) if the test Terraform template is deployed successfully.
- $script:terraformProvisioningState: the provisioning state from test Terraform template deployment, which should be set by the deployment script (deploy-policy-test-terraform-template.ps1).
- $script:terraformViolateDirectoryPath: the directory path for the Terraform configuration used for validate against Policy Violation API that expected to violate deny or audit policies, which should be set to "$PSScriptRoot\$script:GlobalConfig_terraformViolateDirectoryName" by the initiation script (initiate-test.ps1).
- $script:terraformComplyDirectoryPath: the directory path for the Terraform configuration used for validate against Policy Violation API that expected to comply with the policy, which should be set to "$PSScriptRoot\$script:GlobalConfig_terraformComplyDirectoryName" by the initiation script (initiate-test.ps1).

#>

#endregion

#region defining tests
<#
The following policy definitions are tested:.
  - List the policy definitions being tested here.
#>

#define tests
$tests = @()

#endregion

#region Invoke tests - do not modify
$params = @{
  tests         = $tests
  testTitle     = $script:testTitle
  contextTitle  = $script:contextTitle
  testSuiteName = $script:testSuiteName
  OutputFile    = $script:outputFilePath
  OutputFormat  = $script:GlobalConfig_testOutputFormat
}
Test-ARTResourceConfiguration @params

#endregion

#region post-test clean up. - do not modify
Write-Output "Starting post-test cleanup."
. ../.shared/post-test-cleanup.ps1
Write-Output "$script:testTitle test execution completed."
#endregion